# Generated by Django 4.2.7 on 2024-04-14 17:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payouts",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.CharField(
                        choices=[
                            ("BETIKA", "BETIKA"),
                            ("BETGR8", "BETGR8"),
                            ("ODIBETS", "ODIBETS"),
                            ("WINPESA", "WINPESA"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("payout", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Payout",
                "verbose_name_plural": "Payouts",
                "ordering": ("-created_at",),
            },
        ),
    ]
