# Generated by Django 4.2.7 on 2024-04-14 17:42

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("commons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Odibets",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("commons.payouts",),
        ),
    ]
